// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/estimate-fire-number.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var estimate_fire_number_default = defineTool({
  name: "estimate_fire_number",
  title: "Estimate FIRE number",
  description: "Estimate the invested capital required for financial independence from an annual spending level and a safe withdrawal rate (default 4%). Real terms.",
  inputSchema: {
    annualSpending: z.number().finite().positive().max(1e9).describe("Desired annual spending in kroner (real terms, present-day value)."),
    safeWithdrawalRate: z.number().finite().min(1e-4).max(0.2).default(0.04).describe("Safe withdrawal rate as a decimal, e.g. 0.04 for 4%.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ annualSpending, safeWithdrawalRate }) => {
    const fireNumber = annualSpending / safeWithdrawalRate;
    const monthlySpending = annualSpending / 12;
    const summary = `At ${(safeWithdrawalRate * 100).toFixed(2)}% SWR, an annual spending of ${Math.round(annualSpending).toLocaleString("da-DK")} kr (~${Math.round(monthlySpending).toLocaleString("da-DK")} kr/month) requires ~${Math.round(fireNumber).toLocaleString("da-DK")} kr invested.`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: {
        fireNumber: Math.round(fireNumber),
        annualSpending,
        monthlySpending: Math.round(monthlySpending),
        safeWithdrawalRate
      }
    };
  }
});

// src/lib/mcp/tools/project-savings-growth.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var project_savings_growth_default = defineTool2({
  name: "project_savings_growth",
  title: "Project savings growth",
  description: "Project the real (inflation-adjusted) future value of a starting balance plus monthly contributions over N years at a real annual return.",
  inputSchema: {
    startingBalance: z2.number().finite().min(0).max(1e12).describe("Current invested balance in kroner (real terms)."),
    monthlyContribution: z2.number().finite().min(0).max(1e10).describe("Ongoing monthly contribution in kroner (real terms)."),
    years: z2.number().finite().int().positive().max(80).describe("Number of years to project."),
    realAnnualReturn: z2.number().finite().min(-0.2).max(0.5).default(0.04).describe("Expected real annual return as a decimal, e.g. 0.04 for 4%.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ startingBalance, monthlyContribution, years, realAnnualReturn }) => {
    const months = years * 12;
    const rMonthly = Math.pow(1 + realAnnualReturn, 1 / 12) - 1;
    let balance = startingBalance;
    let contributed = 0;
    for (let i = 0; i < months; i++) {
      balance = balance * (1 + rMonthly) + monthlyContribution;
      contributed += monthlyContribution;
    }
    const finalBalance = Math.round(balance);
    const growth = Math.round(balance - startingBalance - contributed);
    const summary = `After ${years} years at ${(realAnnualReturn * 100).toFixed(2)}% real return: ~${finalBalance.toLocaleString("da-DK")} kr (contributed ${Math.round(contributed).toLocaleString("da-DK")} kr, growth ${growth.toLocaleString("da-DK")} kr). Real terms.`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: {
        finalBalance,
        totalContributed: Math.round(contributed),
        growth,
        years,
        realAnnualReturn
      }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "frihedsmodel-mcp",
  title: "Frihedsmodel",
  version: "0.1.0",
  instructions: "Financial-independence planning helpers. Use `estimate_fire_number` to compute the invested capital required to fund a given annual spending at a safe withdrawal rate. Use `project_savings_growth` to project the future real value of a balance plus monthly contributions. All figures are in real (inflation-adjusted) kroner.",
  tools: [estimate_fire_number_default, project_savings_growth_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
